### ISSUE TITLE
Clarify self-message transmission behavior

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#45]
I saw discussion on self-transmission of messages and also commit 189c34d7.

I want to confirm the intention and issues. Especially I want to separate it into two cases:

### Direct-message to self

- intention: it's dumb and wastes server time so ignore them.
- issues: none that I can think of 
- status: this is what the commit above implements

### Broadcast-messages to self (e.g. blame)

- intention: I couldn't come up with a great reason to stop these. Maybe it just seems logical? Does it cause problems for the client?
- issues: nothing in particular but it makes the server slightly more simple to do an actual broadcast
- status: I don't think the current server implements this. [here](https://github.com/cashshuffle/cashshuffle/blob/master/server/broadcast.go#L31)

**Comment by zquestz** [comment]
Yep this is intentional. When someone sends a unicast message it makes no sense for them to send it to themselves, however with broadcast, it is much easier for clients to catch a received message and process it, rather than the sender assuming the action will occur and having to add logic on send then have other clients process it on receive. Therefore I like the current logic, not allowing unicast sending to yourself, but broadcasts go to everyone to simplify the processing of that broadcast.
