### ISSUE TITLE
Feature Request:  Extra verbose debug mode

### ISSUE THREAD

**Issue by alwaysAn0n** [cashshuffle/cashshuffle#68]
I propose an additional flag that allows for extra verbose logs when in debug mode.

In this "extra verbose" mode, I would like to see the following new logs

1. All inbound messages before they are parsed by the server ( as base64 strings )
2. Anything else @emergent-reasons @cculianu ?

This new feature will be a tremendous help when trying to diagnose messaging problems and writing new CashShuffle clients .  It will also help us write documentation and unit tests.  Win-win!

**Comment by emergent-reasons** [comment]
I think this is reasonable, especially as long as code-as-spec is reality. We can do it right after we validate that a received message is structurally valid before sending it off as a packetInfo.

**Comment by emergent-reasons** [comment]
@alwaysAn0n please close if you agree with below.

We have this implemented in #67 but I am going to remove it and leave the code here for the future. The reason is that I think you got the JS lib working already (thank you!) and the byte output in the logs makes it extremely noisy.

If this becomes necessary, we could do this:
- Convert debug from a boolean flag to a level
- level 0 is no debug info
- level 1 is standard debug info (=== current `debug=true`)
- level 2 is matrix operator (show all the bytes for send and receive messages)

For receiving, the place is `messages.go`, `sendToPacketInfoChan()` in the debugMode condition:

```
jsonData, err := json.MarshalIndent(pdata, "", "  ")
if err != nil {
	fmt.Printf("Unable to marshal debug json data: %s\n", err)
} else {
	fmt.Println(jsonData)
}
```
For sending, the place is in `proto.go`, `writeMessage()`, in the debugMode condition:

```
jsonData, err := json.MarshalIndent(packets, "", "  ")
if err != nil {
	fmt.Printf("Unable to marshal debug json data: %s\n", err)
} else {
	fmt.Println(jsonData)
}
```

**Comment by zquestz** [comment]
Done and merged. =)

**Comment by cculianu** [comment]
Sorry I didn't have time to look at this in detail. Been busy with my own stuff. I trust you guys are awesome.
