### ISSUE TITLE
put any singleton/long-term structures on the tracker

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#70]
It might be only the ban cleanup ticker. Behaviorally it does not matter now because the tracker has the same lifespan. For the same reason though, it seems reasonable to explicitly connect them.

@cculianu

**Comment by cculianu** [comment]
Yeah if anything so that maintainers down the road have a slightly easier time when reading the code. "Hidden side-effect" objects can take a little while to discover the existence of when you first start working with a piece of code.

That being said I inserted a bunch of these into EC already for performance reasons but.. EC already is a beast for readability due to the large codebase that was ad-hoc added as needs arose.  It's a drop in the ocean there. but.. here we can do things good from the get-go!
